### PR TITLE
Refactored Equities

### PR DESCRIPTION
**Pull request by colin99d**

### CODE REVIEW

**Comment by colin99d** [comment]
Pandas performance:
%timeit fd.select_equities()
2.16 s ± 6.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit fd.select_equities(country="Germany")
983 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by JerBouma** [comment]
Reminder to self: SQUASH THE THING!

**Comment by colin99d** [comment]
I went ahead and coverted all data to csv. Here are the results:
```
 48K    Categories
4.6M    Cryptocurrencies
1.2M    Currencies
 19M    ETFs
687M    Equities
108M    Funds
 36M    Indices
632K    Moneymarkets
1.4M    cryptos.csv
 92K    currencies.csv
 68M    equities.csv
8.3M    etfs.csv
 41M    funds.csv
5.0M    indices.csv
120K    moneymarkets.csv
```

**Comment by JerBouma** [comment]
Did a little fixy-fix:

```
>>> import financedatabase as fd
>>> equities = fd.Equities()
>>> equities.options(selection='sector', country='united states')
array(['Healthcare', 'Basic Materials', 'Financial Services',
       'Industrials', 'Consumer Defensive', 'Real Estate',
       'Consumer Cyclical', 'Technology', 'Communication Services', nan,
       'Services', 'Utilities', 'Energy', 'Consumer Goods',
       'Industrial Goods', 'Financial', 'Conglomerates'], dtype=object)
>>> equities.options(selection='sector', country='United States')
array(['Healthcare', 'Basic Materials', 'Financial Services',
       'Industrials', 'Consumer Defensive', 'Real Estate',
       'Consumer Cyclical', 'Technology', 'Communication Services', nan,
       'Services', 'Utilities', 'Energy', 'Consumer Goods',
       'Industrial Goods', 'Financial', 'Conglomerates'], dtype=object)
>>> 
```

With:

```
if capitalize:
    country, sector, industry = country.title(), sector.title(), industry.title()
```

Because most of the items are always capitalized, I wanted to make sure that when people do not capitalize it still works. I couldn't find a scenario where sector is capitalized but industry or country isn't so all are in this one but it is an argument people can put to False (True by default).

**Comment by colin99d** [comment]
Looks good to me!

**Comment by JerBouma** [comment]
One last thing though, we need search to work for multiple queries.

**Comment by colin99d** [comment]
Unfortunately `equities` is an instance of the `Equities` class, while search returns a `DataFrame` object. I think the best way to handle this, is to send search terms as kwargs. For example:
```
equities.search(summary="tesla", long_name="exploration")
```
Of course this is not the only solution, I would love to know your thoughts!

**Pull request merged**
